### ISSUE TITLE
example.js don't work

### ISSUE THREAD

**Issue by dennyb** [twitch-irc/twitch-irc#101]
Hey,

I used the example.js from your wiki page. (Of course I changed the username + oauth)
But when I want to start the script, and error occur:

```
# node example.js
[21:30:26] info  - Searching for a Twitch server..
[21:30:26] event - connecting
[21:30:26] event - logon
[21:30:26] error - TypeError: Cannot read property 'tags' of null
    at DestroyableTransform._transform (/var/www/clients/client1/web37/web/node_modules/twitch-irc/node_modules/irc-message/index.js:148:35)
    at DestroyableTransform.Transform._read (/var/www/clients/client1/web37/web/node_modules/twitch-irc/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/var/www/clients/client1/web37/web/node_modules/twitch-irc/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/var/www/clients/client1/web37/web/node_modules/twitch-irc/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/var/www/clients/client1/web37/web/node_modules/twitch-irc/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/var/www/clients/client1/web37/web/node_modules/twitch-irc/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at Socket.pipeOnReadable (_stream_readable.js:643:5)
    at Socket.emit (events.js:92:17)
```

Anyone know why?

Current example.js:
```
var irc = require('twitch-irc');

var clientOptions = {
    options: {
        debug: true,
        debugIgnore: ['ping', 'chat', 'action']
    },
    identity: {
        username: '<username>',
        password: 'oauth:o*****'
    },
    channels: ['channel']
}
var client = new irc.client(clientOptions);

client.connect();

client.addListener('chat', function (channel, user, message) {
    console.log(user.username + ': ' + message);
    if (message.toLowerCase() === '!hello') {
        client.say(channel, 'Hello, ' + user.username + '!');
    }
});
```

**Comment by dennyb** [comment]
Hmm... on local machine the bot starts and connect but keep disconnecting the whole time:
```
[21:46:55] error  - Connection timed out.
[21:46:55] event  - disconnected
[21:46:55] info   - Reconnecting in 10 seconds..
[21:47:05] event  - reconnect
[21:47:05] info   - Searching for a Twitch server..
[21:47:05] event  - connecting
[21:47:05] event  - logon
[21:47:06] raw    - 001: Welcome, GLHF!
[21:47:06] raw    - 002: Your host is tmi.twitch.tv
[21:47:06] raw    - 003: This server is rather new
[21:47:06] raw    - 004: -
[21:47:06] raw    - 375: -
[21:47:06] raw    - 372: You are in a maze of twisty passages, all alike.
[21:47:06] event  - connected
[21:47:06] raw    - 376: >
[21:47:09] event  - join
[21:47:09] raw    - 366: #channel
[21:47:26] error  - Connection timed out.
[21:47:26] event  - disconnected
[21:47:26] info   - Reconnecting in 10 seconds..
[21:47:36] event  - reconnect
[21:47:36] info   - Searching for a Twitch server..
[21:47:36] event  - connecting
[21:47:36] event  - logon
[21:47:37] raw    - 001: Welcome, GLHF!
[21:47:37] raw    - 002: Your host is tmi.twitch.tv
[21:47:37] raw    - 003: This server is rather new
[21:47:37] raw    - 004: -
[21:47:37] raw    - 375: -
[21:47:37] raw    - 372: You are in a maze of twisty passages, all alike.
[21:47:37] event  - connected
[21:47:37] raw    - 376: >
[21:47:40] event  - join
[21:47:40] raw    - 366: #channel
[21:47:57] error  - Connection timed out.
[21:47:57] event  - disconnected
[21:47:57] info   - Reconnecting in 10 seconds..
[21:48:07] event  - reconnect
[21:48:07] info   - Searching for a Twitch server..
```

But what I don't understand:
Log says that the Bot got connection timeout.. but why the hell is he "knowing" chat someone wrote in the chat while he reconnects? Seems little bit weird at the moment..

**Comment by Schmoopiie** [comment]
Not sure what's going on here, make sure you have the latest version of our module (you may also use the version on GitHub), make sure you have the latest version of Node.js or io.js. Your problem might be related to your firewall. Also, the ``TypeError: Cannot read property 'tags' of null`` error is due to some changes Twitch made, see issue #102

**Comment by SimulatedGREG** [comment]
Make sure you have verified your Twitch account through the email they send when registering. Without it, Twitch prevents you from saying anything in any chats. I had this problem when I tried out the example.

**Comment by Schmoopiie** [comment]
Closing this issue, see the last post of issue #106 to fix it.
