### ISSUE TITLE
"TypeError: Cannot read property 'tags' of null" after disconnect

### ISSUE THREAD

**Issue by Lange** [twitch-irc/twitch-irc#102]
Shortly after [this tweet](https://twitter.com/MoobotApp/status/606571500141977600) from Moobot about Twitch silently changing something with chat, my instance of [Streen](https://github.com/SupportClass/streen) (basically just an IPC/RPC wrapper around twitch-irc) crashed with this log:

```
2015-06-04 17:38: warn: DISCONNECTED: Software caused connection abort.
2015-06-04 17:38: error: TypeError: Cannot read property 'tags' of null
    at DestroyableTransform._transform (/home/endofline/streen/node_modules/twitch-irc/node_modules/irc-message/index.js:148:35)
    at DestroyableTransform.Transform._read (/home/endofline/streen/node_modules/twitch-irc/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/endofline/streen/node_modules/twitch-irc/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/endofline/streen/node_modules/twitch-irc/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/endofline/streen/node_modules/twitch-irc/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/home/endofline/streen/node_modules/twitch-irc/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Socket.ondata (_stream_readable.js:520:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at readableAddChunk (_stream_readable.js:145:16)
```

No worries as pm2 just restarted it immediately, but I figured I'd post it here.

**Comment by Schmoopiie** [comment]
Will see what's going on, so many changes on Twitch lately -_-

**Comment by Schmoopiie** [comment]
Oh, turns out it is because the server is down but the port is still open. This is happening with ``192.16.64.145:443`` right now.
