### ISSUE TITLE
Twitched server, no login possible

### ISSUE THREAD

**Issue by EfficiencyVI** [twitch-irc/twitch-irc#115]
Hi,

I have a problem again. I switched the server with the bot. The unmodified stable releases throws this error:

```
[21:17:35] error  - Error: write after end
    at writeAfterEnd (/var/www/domain.com/bot/node_modules/twitch-irc/node_modules/irc-message/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:144:12)
    at DestroyableTransform.Writable.write (/var/www/domain.com/bot/node_modules/twitch-irc/node_modules/irc-message/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:192:5)
    at write (_stream_readable.js:583:24)
    at flow (_stream_readable.js:592:7)
    at Socket.pipeOnReadable (_stream_readable.js:624:5)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
```

The beta release just stops on the login. I can still login with telnet from the new server so the connection is okay. But I cannot login with Twitch-IRC. The old server is working fine. There is no difference in the code.

At this moment, I have no idea how to debug this. Any ideas?

**Comment by celluj34** [comment]
please use tmi.js. There have been changes made to the chat api and twitch-irc will not work without further changes.

**Comment by EfficiencyVI** [comment]
@celluj34 Again: It works on one server (debian 6) but not on the other (Ubuntu 14.04) for no apparent reason and I have no idea how to debug that.

**Comment by EfficiencyVI** [comment]
And just for your information. TMI.js throws this error:

```
[02:06pm] warn: Could not parse NOTICE from tmi.twitch.tv:
[02:06pm] warn: :tmi.twitch.tv NOTICE * :Login unsuccessful
´´´

And that's it. A different account works and a different server works too.

**Comment by AlcaDesign** [comment]
Have you tried getting a new oauth token for the account that can't login?

**Comment by EfficiencyVI** [comment]
I will post my complete data here as my login was changed. It makes no sense but maybe it helps you to find the problem:

```
var options = {
    options: {
        debug: true
    },
    connection: {
        random: "chat",
        reconnect: false,
        server: "199.9.253.119",
        port: 443
    },
    identity: {
        username: "yaybotio",
        password: "ojwjiv0yl55o8ihwwvbloxdh4g1kv6"
    },
    channels: ["#efficiencyvi"]
};
```
Result:
```
[04:04pm] info: Connecting to 192.16.64.145 on port 80..
[04:04pm] info: Sending authentication to server..
[04:04pm] warn: Could not parse NOTICE from tmi.twitch.tv:
[04:04pm] warn: :tmi.twitch.tv NOTICE * :Login unsuccessful
[04:04pm] error: Login unsuccessful.
[04:04pm] info: Connection closed.
```

In comparison:
```
telnet irc.twitch.tv 6667
Trying 192.16.64.145...
Connected to irc.twitch.tv.
Escape character is '^]'.
USER yaybotio
PASS oauth:ojwjiv0yl55o8ihwwvbloxdh4g1kv6
NICK yaybotio
:tmi.twitch.tv 001 yaybotio :Welcome, GLHF!
:tmi.twitch.tv 002 yaybotio :Your host is tmi.twitch.tv
:tmi.twitch.tv 003 yaybotio :This server is rather new
:tmi.twitch.tv 004 yaybotio :-
:tmi.twitch.tv 375 yaybotio :-
:tmi.twitch.tv 372 yaybotio :You are in a maze of twisty passages, all alike.
:tmi.twitch.tv 376 yaybotio :>
JOIN #efficiencyvi
:yaybotio!yaybotio@yaybotio.tmi.twitch.tv JOIN #efficiencyvi
:yaybotio.tmi.twitch.tv 353 yaybotio = #efficiencyvi :yaybotio
:yaybotio.tmi.twitch.tv 366 yaybotio #efficiencyvi :End of /NAMES list
quit
Connection closed by foreign host.
```

This happened for 4 different logins. However with the 5th new login it seems to work for now and I have still no idea why.

**Comment by larzuk91** [comment]
I had connection problems once, and I fixed it using this configuration:

connection: {
        preferredPort: 443,
        preferredServer: '192.16.64.144'
    }

Give it a try
