### ISSUE TITLE
possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by macharborguy** [twitch-irc/twitch-irc#119]
I posted about this some time ago and was told that it was not an actual memory leak, but that it also should have been fixed in the latest version.

I increased the number of listeners to 150, but as you can see in the below warning and trace, it is still topping off the number of active listeners.

``` (node) warning: possible EventEmitter memory leak detected. 151 modsTherobanddanshow listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:179:15)
    at once (events.js:204:8)
    at client.mods (/path_to_my_nodejs_program/node_modules/twitch-irc/libraries/client.js:826:14)
    at Object.modUpdater (/path_to_my_nodejs_program/lib/chatManager.js:389:11)
    at updateMods (/path_to_my_nodejs_program/lib/chatManager.js:397:10)
    at Timer.listOnTimeout (timers.js:110:15)
```

**My Code**
- **updateMods** is a variable that holds a setTimeout, set to expire after 60 seconds
- **modUpdater** is the function that runs when the Timeout in updateMods expires.  It calls the twitch-irc Mods function, and then restarts the setTimeout for another 60 seconds.  I also make sure to clearTimeout on the updateMods variable, as well as set it to null to make sure it is completely cleared

after looking at the twitch-irc Mods function, i can see that it makes use of 'Once', so it *should* only be listening for the returned list of mods that one time, after which it kills the listener, but that does not appear to be happening, at least from the way the warning message is reporting it.

**Comment by celluj34** [comment]
Please do not use twitch-irc anymore. please move to tmi.js

Joseph Cellucci
Software Developer
ITA Group
celluj34@gmail.com

**Comment by macharborguy** [comment]
How many of the current Twitch-IRC features are part of the current, work in progress, version of tmi.js?  If twitch-irc is no longer being developed, and tmi.js is set to become its eventual replacement, ill go in and mess around with the twitch-irc mod handling and wait for tmi.js to have a little more documentation before I jump head first into it.

**Comment by celluj34** [comment]
As far as I know, there should not be any missing features. There are
changes to the user object that you have to code around, but that was done
by twitch.

**Comment by macharborguy** [comment]
just attempted to install tmi.js and i got a warning about an optional dependency failing, looks like 'node-icu-charset-detector' to be specific

```
> bufferutil@1.1.0 install /largeStore/nodeJS/RADBot-2015/node_modules/tmi.js/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/largeStore/nodeJS/RADBot-2015/node_modules/tmi.js/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory `/largeStore/nodeJS/RADBot-2015/node_modules/tmi.js/node_modules/ws/node_modules/bufferutil/build'

> utf-8-validate@1.1.0 install /largeStore/nodeJS/RADBot-2015/node_modules/tmi.js/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/largeStore/nodeJS/RADBot-2015/node_modules/tmi.js/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/largeStore/nodeJS/RADBot-2015/node_modules/tmi.js/node_modules/ws/node_modules/utf-8-validate/build'

> dtrace-provider@0.5.0 install /largeStore/nodeJS/RADBot-2015/node_modules/tmi.js/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js


> node-icu-charset-detector@0.1.0 install /largeStore/nodeJS/RADBot-2015/node_modules/tmi.js/node_modules/irc/node_modules/node-icu-charset-detector
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/largeStore/nodeJS/RADBot-2015/node_modules/tmi.js/node_modules/irc/node_modules/node-icu-charset-detector/build'
  CXX(target) Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o
../node-icu-charset-detector.cpp:7:28: fatal error: unicode/ucsdet.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o] Error 1
make: Leaving directory `/largeStore/nodeJS/RADBot-2015/node_modules/tmi.js/node_modules/irc/node_modules/node-icu-charset-detector/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /largeStore/nodeJS/RADBot-2015/node_modules/tmi.js/node_modules/irc/node_modules/node-icu-charset-detector
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

> iconv@2.1.8 install /largeStore/nodeJS/RADBot-2015/node_modules/tmi.js/node_modules/irc/node_modules/iconv
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/largeStore/nodeJS/RADBot-2015/node_modules/tmi.js/node_modules/irc/node_modules/iconv/build'
  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  AR(target) Release/obj.target/iconv.a
  COPY Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/iconv.node
  SOLINK_MODULE(target) Release/obj.target/iconv.node: Finished
  COPY Release/iconv.node
make: Leaving directory `/largeStore/nodeJS/RADBot-2015/node_modules/tmi.js/node_modules/irc/node_modules/iconv/build'
npm WARN optional dep failed, continuing node-icu-charset-detector@0.1.0
tmi.js@0.0.16 node_modules/tmi.js
├── locallydb@0.0.9
├── vow@0.4.10
├── underscore@1.8.3
├── irc-message@3.0.1 (iso8601-convert@1.0.0, irc-prefix-parser@1.0.1, through2@0.6.5)
├── underscore.string@3.1.1
├── cron@1.0.9 (moment-timezone@0.3.1)
├── ws@0.7.2 (options@0.0.6, ultron@1.0.2, bufferutil@1.1.0, utf-8-validate@1.1.0)
├── bunyan@1.4.0 (safe-json-stringify@1.0.3, mv@2.1.1, dtrace-provider@0.5.0)
└── irc@0.3.12 (ansi-color@0.2.1, irc-colors@1.2.0, iconv@2.1.8)
```

**Comment by AlcaDesign** [comment]
The install was successful, it should be fine to work with.

**Comment by macharborguy** [comment]
first issue i appear to be running into after swapping over the code is that i do not seem to be able to log into 2 accounts at the same time.  I would normally connect to both our primary streaming account, "TheRobAndDanShow" (for the hosting notifications) and to our bot account "RAD_Bot" which handles all of our bot related features.  I am able to connect with the RAD_Bot portion fine, but TheRobAndDanShow connection reports a login unsuccessful.

The IRC connections are being stored as folllows...

```
var rad_irc = irc.client(ircOptions);
var rnd_irc = irc.client(ircOptions2);
```

rad_irc being radbot, and rnd_irc being the primary streaming account.

I am initiating the connections in the same order...

```
rad_irc.connect();
rnd_irc.connect();
```

**Comment by AlcaDesign** [comment]
You need to instantiate the client. Use `new irc.client(...)`

**Comment by macharborguy** [comment]
sorry, that was a typo on my part.  here is the direct copy-page from the code.

```
var rad_irc = new irc.client(ircOptions);
var rnd_irc = new irc.client(ircOptions2);
```

**Comment by AlcaDesign** [comment]
I was able to make it work just fine
![working](http://i.gyazo.com/b698bc519964fd6f1dd1a16cef9f2c40.png)

```javascript
var tmi = require('tmi.js'),
	botOptions = {
			identity: {
					username: 'botName',
					password: 'oauth:botOauth'
				},
			channels: ['channel']
		},
	priOptions = {
			identity: {
					username: 'primaryName',
					password: 'oauth:primaryOauth'
				},
			channels: ['channel']
		},

	bot = new tmi.client(botOptions),
	pri = new tmi.client(priOptions);

bot.connect();
pri.connect();

bot.on('chat', function(channel, user, message) {
		console.log('[bot]', channel, user.username, message);
	});
pri.on('chat', function(channel, user, message) {
		console.log('[pri]', channel, user.username, message);
	});
```
